Repository bitfireAT/icsx5, pull requests merged in 2024-05, with the labels that each got.

#310 [Severe] Editing/Deleting subscriptions doesn't update the UI
  app/src/main/java/at/bitfire/icsdroid/ui/views/EditCalendarActivity.kt
Labels: bug

#323 Task result is based on sync status
  app/build.gradle.kts
  app/src/androidTest/java/at/bitfire/icsdroid/BaseSyncWorkerTest.kt
  app/src/androidTest/res/raw/sample.ics
  app/src/main/java/at/bitfire/icsdroid/BaseSyncWorker.kt
  app/src/main/java/at/bitfire/icsdroid/ProcessEventsTask.kt
  gradle/libs.versions.toml
Labels: enhancement

#320 EditCalendarActvivity: Switch to compose state and kotlin flows
  app/src/main/java/at/bitfire/icsdroid/model/EditCalendarModel.kt
  app/src/main/java/at/bitfire/icsdroid/ui/screen/EditCalendarScreen.kt
  app/src/main/java/at/bitfire/icsdroid/ui/views/EditCalendarActivity.kt
  app/src/main/java/at/bitfire/icsdroid/ui/views/SubscriptionSettingsComposable.kt
Labels: refactoring

#334 Fix workers piling up
  app/src/main/java/at/bitfire/icsdroid/PeriodicSyncWorker.kt
Labels: bug

#335 Stop subscription form covering the loading indicator
  app/src/main/java/at/bitfire/icsdroid/ui/views/EnterUrlComposable.kt
Labels: bug

#339 Stop requesting legacy external storage
  app/src/main/AndroidManifest.xml
Labels: refactoring
