Repository bitfireAT/icsx5, pull requests merged in 2025-06, with the labels that each got.

#581 Fix lint warnings
  app/src/main/java/at/bitfire/icsdroid/ui/InfoActivity.kt
Labels: refactoring

#595 Collect flow in viewModel only when needed
  app/src/main/java/at/bitfire/icsdroid/db/dao/SubscriptionsDao.kt
  app/src/main/java/at/bitfire/icsdroid/model/EditSubscriptionModel.kt
  app/src/main/java/at/bitfire/icsdroid/ui/screen/EditCalendarScreen.kt
Labels: bug

#596 JSON backup import and export
  app/src/androidTest/java/at/bitfire/icsdroid/db/entity/TestSubscription.kt
  app/src/main/java/at/bitfire/icsdroid/JsonUtils.kt
  app/src/main/java/at/bitfire/icsdroid/db/dao/SubscriptionsDao.kt
  app/src/main/java/at/bitfire/icsdroid/db/entity/Subscription.kt
  app/src/main/java/at/bitfire/icsdroid/model/SubscriptionsModel.kt
  app/src/main/java/at/bitfire/icsdroid/ui/screen/CalendarListScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#603 Use Hilt for DI
  app/build.gradle.kts
  app/src/androidTest/java/at/bitfire/icsdroid/BaseSyncWorkerTest.kt
  app/src/androidTest/java/at/bitfire/icsdroid/HiltTestRunner.kt
  app/src/androidTest/java/at/bitfire/icsdroid/TestSyncWorker.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/at/bitfire/icsdroid/App.kt
  app/src/main/java/at/bitfire/icsdroid/BaseSyncWorker.kt
  app/src/main/java/at/bitfire/icsdroid/PeriodicSyncWorker.kt
  app/src/main/java/at/bitfire/icsdroid/ProcessEventsTask.kt
  app/src/main/java/at/bitfire/icsdroid/SyncWorker.kt
  app/src/main/java/at/bitfire/icsdroid/db/AppDatabase.kt
  app/src/main/java/at/bitfire/icsdroid/model/CreateSubscriptionModel.kt
  app/src/main/java/at/bitfire/icsdroid/model/CredentialsModel.kt
  app/src/main/java/at/bitfire/icsdroid/model/EditSubscriptionModel.kt
  app/src/main/java/at/bitfire/icsdroid/model/SubscriptionSettingsModel.kt
  app/src/main/java/at/bitfire/icsdroid/model/SubscriptionsModel.kt
  app/src/main/java/at/bitfire/icsdroid/model/ThemeModel.kt
  app/src/main/java/at/bitfire/icsdroid/model/ValidationModel.kt
  app/src/main/java/at/bitfire/icsdroid/ui/screen/EditCalendarScreen.kt
  app/src/main/java/at/bitfire/icsdroid/ui/theme/Theme.kt
  app/src/main/java/at/bitfire/icsdroid/ui/views/AddCalendarActivity.kt
  app/src/main/java/at/bitfire/icsdroid/ui/views/CalendarListActivity.kt
  app/src/main/java/at/bitfire/icsdroid/ui/views/EditCalendarActivity.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: refactoring

#609 Update dead transifex link
  README.md
Labels: bug
